import React, { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { dateForYear, getDisplayYearsRange, getPreviewText, mergeEntriesByLatestUpdatedAt, toDateISO, parseDateISO, type DisplayYears } from './diaryLogic';
import './styles.css';

type Photo = { id: string; uri: string; width?: number; height?: number; createdAt: string };
type Entry = { id: string; dateISO: string; body: string; photos: Photo[]; createdAt: string; updatedAt: string };
type Settings = { displayYears: DisplayYears; theme: 'warm-analog' };
type Route = { name: 'date'; dateISO: string } | { name: 'calendar' } | { name: 'settings' } | { name: 'edit'; dateISO: string } | { name: 'photos'; dateISO: string; index: number };

const DB = 'warm-paper-diary';
const STORE = 'entries';
const SETTINGS = 'warm-paper-diary:settings';
const WEEKDAYS = ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'];
const DAYS = ['일', '월', '화', '수', '목', '금', '토'];
let dbp: Promise<IDBDatabase> | null = null;

function todayISO() { return toDateISO(new Date()); }
function fmtMD(iso: string) { const d = parseDateISO(iso); return String(d.getMonth() + 1) + '월 ' + String(d.getDate()) + '일'; }
function fmtTitle(iso: string) { const d = parseDateISO(iso); return String(d.getMonth() + 1) + '월 ' + String(d.getDate()) + '일 · ' + String(d.getFullYear()); }
function fmtFull(iso: string) { const d = parseDateISO(iso); return String(d.getFullYear()) + '년 ' + String(d.getMonth() + 1) + '월 ' + String(d.getDate()) + '일'; }
function nav(hash: string) { window.location.hash = hash; }
function route(): Route { const p = window.location.hash.replace(/^#\/?/, '').split('/').filter(Boolean); if (p[0] === 'calendar') return { name: 'calendar' }; if (p[0] === 'settings') return { name: 'settings' }; if (p[0] === 'edit') return { name: 'edit', dateISO: p[1] || todayISO() }; if (p[0] === 'photos') return { name: 'photos', dateISO: p[1] || todayISO(), index: Number(p[2] || 0) }; if (p[0] === 'date') return { name: 'date', dateISO: p[1] || todayISO() }; return { name: 'date', dateISO: todayISO() }; }

function openDB(): Promise<IDBDatabase> { if (dbp) return dbp; dbp = new Promise((res, rej) => { const r = indexedDB.open(DB, 1); r.onupgradeneeded = () => { const db = r.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE, { keyPath: 'dateISO' }); }; r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); }); return dbp; }
async function tx<T>(mode: IDBTransactionMode, work: (s: IDBObjectStore) => IDBRequest<T>): Promise<T> { const db = await openDB(); return new Promise((res, rej) => { const t = db.transaction(STORE, mode); const req = work(t.objectStore(STORE)); req.onsuccess = () => res(req.result); req.onerror = () => rej(req.error); t.onerror = () => rej(t.error); }); }
async function allEntries(): Promise<Entry[]> { const rows = await tx<Entry[]>('readonly', s => s.getAll()); return rows.sort((a, b) => b.dateISO.localeCompare(a.dateISO)); }
async function getEntry(dateISO: string) { return tx<Entry | undefined>('readonly', s => s.get(dateISO)); }
async function saveEntry(dateISO: string, body: string, photos: Photo[]) { const old = await getEntry(dateISO); const clean = body.trim(); const safePhotos = photos.filter(p => p.uri); if (!clean && safePhotos.length === 0) { if (old) await tx<undefined>('readwrite', s => s.delete(dateISO)); return; } const now = new Date().toISOString(); const entry: Entry = { id: old?.id || crypto.randomUUID(), dateISO, body: clean, photos: safePhotos, createdAt: old?.createdAt || now, updatedAt: now }; await tx<IDBValidKey>('readwrite', s => s.put(entry)); return entry; }
async function putMany(entries: Entry[]) { const db = await openDB(); await new Promise<void>((res, rej) => { const t = db.transaction(STORE, 'readwrite'); const s = t.objectStore(STORE); entries.forEach(e => s.put(e)); t.oncomplete = () => res(); t.onerror = () => rej(t.error); }); }
function getSettings(): Settings { try { const raw = localStorage.getItem(SETTINGS); const parsed = raw ? JSON.parse(raw) : {}; return { displayYears: parsed.displayYears === 10 || parsed.displayYears === 'all' ? parsed.displayYears : 5, theme: 'warm-analog' }; } catch { return { displayYears: 5, theme: 'warm-analog' }; } }
function setSettings(settings: Settings) { localStorage.setItem(SETTINGS, JSON.stringify(settings)); return settings; }
function normalizePhoto(v: any): Photo | null { if (!v || typeof v.uri !== 'string' || !v.uri) return null; return { id: typeof v.id === 'string' ? v.id : crypto.randomUUID(), uri: v.uri, width: typeof v.width === 'number' ? v.width : undefined, height: typeof v.height === 'number' ? v.height : undefined, createdAt: typeof v.createdAt === 'string' ? v.createdAt : new Date().toISOString() }; }
function normalizeEntry(v: any): Entry | null { if (!v || typeof v.dateISO !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(v.dateISO)) return null; const photos = Array.isArray(v.photos) ? v.photos.map(normalizePhoto).filter(Boolean) as Photo[] : []; const body = typeof v.body === 'string' ? v.body.trim() : ''; if (!body && photos.length === 0) return null; const now = new Date().toISOString(); return { id: typeof v.id === 'string' ? v.id : crypto.randomUUID(), dateISO: v.dateISO, body, photos, createdAt: typeof v.createdAt === 'string' ? v.createdAt : now, updatedAt: typeof v.updatedAt === 'string' ? v.updatedAt : now }; }
function readBackup(text: string) { let data: any; try { data = JSON.parse(text); } catch { throw new Error('JSON 파일을 읽을 수 없습니다.'); } if (!data || data.schemaVersion !== 1 || !Array.isArray(data.entries)) throw new Error('따뜻한 기록 백업 파일 형식이 아닙니다.'); const settings = data.settings || {}; return { entries: data.entries.map(normalizeEntry).filter(Boolean) as Entry[], settings: { displayYears: settings.displayYears === 10 || settings.displayYears === 'all' ? settings.displayYears : 5, theme: 'warm-analog' as const } }; }
function readPhoto(file: File): Promise<Photo | null> { if (!file.type.startsWith('image/')) return Promise.resolve(null); return new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res({ id: crypto.randomUUID(), uri: String(r.result), createdAt: new Date().toISOString() }); r.onerror = () => rej(r.error); r.readAsDataURL(file); }); }

function BottomNav({ active }: { active: string }) { const items = [['날짜', '◐', '#/'], ['달력', '▦', '#/calendar'], ['쓰기', '✎', '#/edit/' + todayISO()], ['설정', '⚙', '#/settings']]; return <nav className='bottom-nav'>{items.map(i => <button key={i[0]} className={active === i[0] ? 'is-active' : ''} onClick={() => nav(i[2])}><span>{i[1]}</span><em>{i[0]}</em></button>)}</nav>; }
function WarmButton(props: React.PropsWithChildren<React.ButtonHTMLAttributes<HTMLButtonElement> & { soft?: boolean }>) { const { soft, children, ...rest } = props; return <button className={'warm-button ' + (soft ? 'warm-button--soft' : 'warm-button--primary')} {...rest}>{children}</button>; }
function Home({ dateISO }: { dateISO: string }) { const [entries, setEntries] = useState<Entry[]>([]); const [settings, setSet] = useState(getSettings()); useEffect(() => { allEntries().then(setEntries); setSet(getSettings()); }, [dateISO]); const slots = useMemo(() => getDisplayYearsRange(dateISO, settings.displayYears, entries).map(year => { const d = dateForYear(dateISO, year); return { year, dateISO: d, entry: d ? entries.find(e => e.dateISO === d) : undefined }; }), [dateISO, settings, entries]); const move = (n: number) => { const d = parseDateISO(dateISO); d.setDate(d.getDate() + n); window.history.replaceState(null, '', '#/date/' + toDateISO(d)); window.dispatchEvent(new HashChangeEvent('hashchange')); }; return <div className='screen with-bottom-nav'><header className='home-header'><div><h1>{fmtMD(dateISO)}</h1><p>{WEEKDAYS[parseDateISO(dateISO).getDay()]}</p></div><div className='home-header__actions'><WarmButton onClick={() => nav('#/date/' + todayISO())}>오늘</WarmButton><button className='icon-button' onClick={() => nav('#/settings')}>⚙</button></div></header><button className='edge-chevron edge-chevron--left' onClick={() => move(-1)}>‹</button><button className='edge-chevron edge-chevron--right' onClick={() => move(1)}>›</button><section className='year-list'>{slots.map(s => s.entry ? <article className='year-card year-card--filled' key={s.year} onClick={() => nav('#/edit/' + s.entry!.dateISO)}><button className='year-card__thumb' onClick={e => { e.stopPropagation(); if (s.entry!.photos[0]) nav('#/photos/' + s.entry!.dateISO + '/0'); }}>{s.entry.photos[0] ? <img src={s.entry.photos[0].uri} alt='기록 사진' /> : <span />}</button><div className='year-card__body'><h2>{s.year}</h2><p>{getPreviewText(s.entry.body)}</p><small>{s.entry.photos.length ? '사진 ' + s.entry.photos.length + '장' : '글 기록'}</small></div></article> : <button className='year-card year-card--empty' key={s.year} disabled={!s.dateISO} onClick={() => s.dateISO && nav('#/edit/' + s.dateISO)}><div className='year-card__thumb year-card__thumb--empty'><span /></div><div className='year-card__body'><h2>{s.year}</h2><p>{s.dateISO ? '아직 이 날의 기록이 없어요' : '이 해에는 2월 29일이 없어요'}</p><small>{s.dateISO ? '이 날 기록 남기기' : '해당 날짜 없음'}</small></div></button>)}</section><button className='fab' onClick={() => nav('#/edit/' + todayISO())}><span>✎</span><em>오늘 쓰기</em></button><BottomNav active='날짜' /></div>; }
function Editor({ dateISO }: { dateISO: string }) { const [picked, setPicked] = useState(dateISO); const [body, setBody] = useState(''); const [photos, setPhotos] = useState<Photo[]>([]); const [error, setError] = useState(''); useEffect(() => { setPicked(dateISO); getEntry(dateISO).then(e => { setBody(e?.body || ''); setPhotos(e?.photos || []); }); }, [dateISO]); const add = async (files: FileList) => { try { const next = (await Promise.all(Array.from(files).map(readPhoto))).filter(Boolean) as Photo[]; setPhotos(p => p.concat(next)); } catch { setError('사진을 추가하지 못했습니다.'); } }; const save = async () => { try { await saveEntry(picked, body, photos); nav('#/date/' + picked); } catch { setError('저장에 실패했습니다.'); } }; return <div className='screen editor-screen'><header className='editor-header'><button className='icon-button' onClick={() => nav('#/date/' + picked)}>←</button><strong>{fmtTitle(picked)}</strong><WarmButton onClick={save}>저장</WarmButton></header><main className='editor-body'><label className='date-chip'><span>{fmtTitle(picked)}</span><input type='date' value={picked} onChange={e => setPicked(e.currentTarget.value)} /></label><div className='photo-strip'>{photos.map((p, i) => <div className='photo-thumb' key={p.id}><button className='photo-thumb__image' onClick={() => nav('#/photos/' + picked + '/' + i)}><img src={p.uri} alt='다이어리 사진' /></button><button className='photo-thumb__remove' onClick={() => setPhotos(xs => xs.filter(x => x.id !== p.id))}>×</button></div>)}<label className='add-photo-tile'><input type='file' accept='image/*' multiple onChange={(e: ChangeEvent<HTMLInputElement>) => { if (e.currentTarget.files) add(e.currentTarget.files); e.currentTarget.value = ''; }} /><span>＋</span><em>사진</em></label></div><textarea className='writing-area' value={body} onChange={e => setBody(e.currentTarget.value)} placeholder='오늘 하루를 적어보세요' /><p className='storage-note'>글과 사진은 이 기기의 브라우저 저장소에만 저장됩니다.</p>{error && <p className='error-message'>{error}</p>}</main></div>; }
function Viewer({ dateISO, index }: { dateISO: string; index: number }) { const [entry, setEntry] = useState<Entry>(); const [i, setI] = useState(index); useEffect(() => { getEntry(dateISO).then(setEntry); }, [dateISO]); const photos = entry?.photos || []; const photo = photos[i] || photos[0]; return <div className='photo-viewer'><button className='photo-viewer__close' onClick={() => nav('#/date/' + dateISO)}>×</button>{photo ? <img className='photo-viewer__image' src={photo.uri} alt='확대된 사진' /> : <p>사진이 없습니다.</p>}<div className='photo-viewer__dots'>{photos.map((p, n) => <button key={p.id} className={n === i ? 'is-active' : ''} onClick={() => setI(n)} />)}</div><p className='photo-viewer__caption'>{fmtFull(dateISO)}</p></div>; }
function Calendar() { const now = new Date(); const [cursor, setCursor] = useState({ y: now.getFullYear(), m: now.getMonth() }); const [entries, setEntries] = useState<Entry[]>([]); useEffect(() => { allEntries().then(setEntries); }, []); const byDate = new Map(entries.filter(e => e.dateISO.startsWith(String(cursor.y) + '-' + String(cursor.m + 1).padStart(2, '0'))).map(e => [e.dateISO, e])); const first = new Date(cursor.y, cursor.m, 1); const start = new Date(cursor.y, cursor.m, 1 - first.getDay()); const cells = Array.from({ length: 42 }, (_, n) => { const d = new Date(start); d.setDate(start.getDate() + n); return { iso: toDateISO(d), day: d.getDate(), inMonth: d.getMonth() === cursor.m }; }); const move = (n: number) => setCursor(c => { const d = new Date(c.y, c.m + n, 1); return { y: d.getFullYear(), m: d.getMonth() }; }); return <div className='screen with-bottom-nav'><header className='calendar-header'><h1>기록 달력</h1><div className='month-switcher'><button onClick={() => move(-1)}>‹</button><strong>{cursor.y + '년 ' + (cursor.m + 1) + '월'}</strong><button onClick={() => move(1)}>›</button></div></header><section className='calendar-card'><div className='weekday-row'>{DAYS.map(d => <span key={d}>{d}</span>)}</div><div className='month-grid'>{cells.map(c => { const e = byDate.get(c.iso); const p = e?.photos[0]; return <button key={c.iso} className={'calendar-cell ' + (c.inMonth ? '' : 'is-muted') + (c.iso === todayISO() ? ' is-today' : '')} onClick={() => nav(e ? '#/date/' + c.iso : '#/edit/' + c.iso)}><span>{c.day}</span>{p ? <img src={p.uri} alt='기록 사진' /> : e ? <i /> : null}</button>; })}</div></section><BottomNav active='달력' /></div>; }
function SettingsScreen() { const [settings, setLocal] = useState(getSettings()); const [msg, setMsg] = useState(''); const [err, setErr] = useState(''); const input = useRef<HTMLInputElement>(null); const exp = async () => { const entries = await allEntries(); const data = { schemaVersion: 1, exportedAt: new Date().toISOString(), entries, settings }; const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'warm-paper-diary-' + data.exportedAt.slice(0, 10) + '.json'; a.click(); URL.revokeObjectURL(url); setMsg('JSON 백업 파일을 내보냈습니다.'); }; const imp = async (e: ChangeEvent<HTMLInputElement>) => { const f = e.currentTarget.files?.[0]; e.currentTarget.value = ''; if (!f) return; try { const b = readBackup(await f.text()); const merged = mergeEntriesByLatestUpdatedAt(await allEntries() as any, b.entries as any) as Entry[]; await putMany(merged); setLocal(setSettings(b.settings)); setMsg('가져오기 완료: 기록 ' + b.entries.length + '개를 확인했습니다.'); } catch (x) { setErr(x instanceof Error ? x.message : '가져오기에 실패했습니다.'); } }; return <div className='screen settings-screen with-bottom-nav'><header className='settings-header'><h1>설정</h1><p>따뜻한 종이 다이어리처럼 조용히 저장해요.</p></header><section className='settings-section'><h2>백업</h2><button className='settings-row' onClick={exp}><span>내보내기</span><em>JSON</em></button><button className='settings-row' onClick={() => input.current?.click()}><span>가져오기</span><em>JSON</em></button><input ref={input} hidden type='file' accept='application/json,.json' onChange={imp} /><p className='settings-help'>사진은 브라우저 로컬 데이터 URI로 저장됩니다. 사진 파일 포함 ZIP 백업은 추후 확장할 수 있습니다.</p></section><section className='settings-section'><h2>표시</h2><div className='segmented'>{([5, 10, 'all'] as DisplayYears[]).map(v => <button key={String(v)} className={settings.displayYears === v ? 'is-active' : ''} onClick={() => setLocal(setSettings({ displayYears: v, theme: 'warm-analog' }))}>{v === 'all' ? '전체' : String(v) + '년'}</button>)}</div><div className='settings-row'><span>테마</span><em>Warm Analog</em></div></section><section className='settings-section'><h2>정보</h2><div className='settings-row'><span>앱 정보</span><em>v{__APP_VERSION__}</em></div><p className='settings-help'>서버 없이 IndexedDB와 localStorage에만 저장됩니다. 브라우저 데이터 삭제나 기기 변경 전 JSON 백업을 해 주세요.</p></section>{msg && <p className='success-message'>{msg}</p>}{err && <p className='error-message'>{err}</p>}<BottomNav active='설정' /></div>; }
function App() { const [r, setR] = useState<Route>(route()); useEffect(() => { const h = () => setR(route()); window.addEventListener('hashchange', h); return () => window.removeEventListener('hashchange', h); }, []); if (r.name === 'calendar') return <div className='app-shell'><Calendar /></div>; if (r.name === 'settings') return <div className='app-shell'><SettingsScreen /></div>; if (r.name === 'edit') return <div className='app-shell'><Editor dateISO={r.dateISO} /></div>; if (r.name === 'photos') return <div className='app-shell'><Viewer dateISO={r.dateISO} index={r.index} /></div>; return <div className='app-shell'><Home dateISO={r.dateISO} /></div>; }
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register(import.meta.env.BASE_URL + 'sw.js', { scope: import.meta.env.BASE_URL }).catch(() => undefined));
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
